name: Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container: amutake/satysfi

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install nodejs pandoc build-essential -y
    - uses: actions/checkout@v4
    - name: link SATySFi
      run: ln -s /root/.opam/*/bin/satysfi /usr/local/bin/satysfi
    - name: link SATySFi libraries
      run: |
        mkdir -p /usr/local/share/satysfi/
        ln -s /root/.satysfi/dist /usr/local/share/satysfi/dist
    - name: Build README
      run: make
