name: Build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    container: amutake/satysfi

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install nodejs pandoc build-essential -y
    - uses: actions/checkout@v2.3.4
    - name: link SATySFi
      run : sudo ln -s /home/opam/.opam/*/bin/satysfi /usr/local/bin/satysfi
    - name: Build README
      run: make
